# FIXME! How can we avoid DRY here? The only difference is that we want to
# include more Perl versions.

name: CI for Pushes

on:
  push:
    branches: [ '*' ]

jobs:
  on-push:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl-version:
        - '5.38'

    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 'Perl version'
      run: perl -V

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: 'Install dependencies'
      run: cpanm --notest --installdeps --verbose .

    - name: 'Prepare build'
      run: perl Build.PL

    - name: 'Build'
      run: perl Build

    - name: 'Test'
      run: prove -wlmbv

