name: CI on Pull Request

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  on-pull-request:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        # perl-version should always be one behind the latest version.  The
        # latest version is tested in the workflow triggered by the push.
        perl-version:
        - '5.36'
        - '5.34'
        - '5.32'
        - '5.30'
        - '5.28'
        - '5.26'
        - '5.24'
        - '5.22'
        - '5.20'
        - '5.18'
        - '5.16'
        - '5.14'
        include:
        - perl-version: '5.38'
          os: ubuntu-latest
          coverage: true

    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 'Perl version'
      run: perl -V

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: 'Installing dependencies'
      run: cpanm --notest --installdeps --verbose .

    - name: 'Prepare build'
      run: perl Build.PL

    - name: 'Build'
      run: perl Build

    - name: 'Test'
      run: prove -wlmbv

    - name: 'Test with coverage'
      if: ${{ matrix.coverage }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cpanm -n Devel::Cover::Report::Coveralls
        cover -test -report Coveralls

